name = "ExactODEReduction"
uuid = "790186a0-1ec0-11ec-1f13-43a2532b2fa8"
authors = ["x3042", "sumiya11", "pogudingleb"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
BloomFilters = "d3d7f49f-8593-5289-ba71-9c4f4848f489"
CustomUnitRanges = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
julia = "1.6"
